### ISSUE TITLE
Tenho tentado usar esta API com o SAGE 50c com o Visual Studio 2019.

### ISSUE THREAD

**Issue by augcampos** [sage-portugal/Retail-API#4]
Tenho tentado usar esta API com o SAGE 50c  com o Visual Studio 2019 e no exemplo inicial na consola falha na initialization.

Conseguimos desenvolver com o VS2019?
Posso usar os exeplos fornecidos? Ou onde posso encontrar um exemplo?
Qual o Codigo/ID da empresa de demostração (999999990 não deu)?

Obrigado

**Comment by ajteixeira** [comment]
O código exemplo para a API da Sage 50c encontra-se aqui:
https://github.com/sage-portugal/50c-API

O código da empresa a passar à API é a sigla. Pode ser encontrada na barra de título da aplicação (exemplo: [DEMO - Empresa de demonstração] - Neste caso: DEMO) ou a área de sistema quando é aberta a ficha da empresa.
